### ISSUE TITLE
make checklist categories list an Accordion component

### ISSUE THREAD

**Issue by blockisec** [PeCoReT/pecoret#121]
### Give a brief summary

use an accordion component for the Checklist-> Categories list

### Additional Information

https://primevue.org/accordion/

**Comment by martin0604** [comment]
Hi, I would like to contribute. This is my first time.

**Comment by blockisec** [comment]
Hi, thank you for supporting the project. A guide should be available in the [docs](https://pecoret.github.io/docs/development-guide/environment-setup/) :)
