### ISSUE TITLE
Can't login after docker installation

### ISSUE THREAD

**Issue by lululunaa** [PeCoReT/pecoret#169]
### Summary

After downloading the docker-compose.yaml file and running docker compose up, the install seems to go fine. I have tried to use the default username and passwords present in the yaml file, and changed them to custom values but neither option seems to work (A message pops up saying unauthenticated). The output/docker logs show the server has been started and is listening:
```
Starting server
[2024-02-11 14:47:22 +0000] [11] [INFO] Starting gunicorn 21.2.0
[2024-02-11 14:47:22 +0000] [11] [INFO] Listening at: http://0.0.0.0:8000 (11)
[2024-02-11 14:47:22 +0000] [11] [INFO] Using worker: sync
[2024-02-11 14:47:22 +0000] [12] [INFO] Booting worker with pid: 12
```
There is only one warning present in any of the docker logs which is:
```
/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported. 
warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
```
After changing the email in the yaml, I attempted to reset my password using the newly entered email address and got no message delivered to my email. I saw in the database, the users `admin` and `Ghost` exist but I cannot login to the application.
Is there something I am missing or doing wrong?

**Comment by blockisec** [comment]
Hi, thanks for reporting this issue.
To receive emails you must configure it in the django settings file. To receive the mail in the console for debugging, you could add `EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"` to the django settings file.
I just tested the default docker-compose file and I can login, so it may be related to your setup.
Is there any error in the browsers dev console?

**Comment by lululunaa** [comment]
What user/credentials should we be using to login to the application? I don't see that information in the documentation anywhere, and I can't create a new user without first getting access to it. There are no errors when navigating to the application, but when I login I just get a 403.

**Comment by blockisec** [comment]
The login should be working with the credentials from the docker-compose file.
In the default compose file the credentials are `admin:dontusethispasswordtoo`. 
I will update the docs with this information.
The URL seems to be not "localhost". You may need to change the CORS and Allowed Hosts settings in django.
This is an example from my `volumes/server/conf/production.py` file which allows login using the previously mentioned credentials using "http://ubuntu"

```python
CSRF_TRUSTED_ORIGINS = ['http://ubuntu', 'http://localhost']
CORS_ALLOWED_ORIGINS = ['http://ubuntu', 'http://localhost']
ALLOWED_HOSTS = ['backend', 'ubuntu']
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
DEBUG = False
```

**Comment by blockisec** [comment]
were you able to solve your problem?

**Comment by blockisec** [comment]
I am closing this issue because of missing information.
